const { Voucher } = require('../models');
const logger = require('../utils/logger');
const { generateSerialNumber, generatePinCode, generateVoucherCode } = require('../utils/generators');

/**
 * Voucher Service - Handles voucher lifecycle and validation
 */
const VoucherService = {
  /**
   * Validate a voucher's serial and PIN
   * @param {string} serialNumber 
   * @param {string} pinCode 
   */
  async validateVoucher(serialNumber, pinCode) {
    try {
      const voucher = await Voucher.findBySerialAndPin(serialNumber, pinCode);
      
      if (!voucher) {
        return { valid: false, message: 'Invalid serial number or PIN code' };
      }

      if (voucher.isUsed) {
        return { valid: false, message: 'This voucher has already been used' };
      }

      if (voucher.deactivatedAt) {
        return { valid: false, message: 'This voucher has been deactivated' };
      }

      const expiryDate = new Date(voucher.expiresAt);
      if (expiryDate < new Date()) {
        return { valid: false, message: `This voucher expired on ${expiryDate.toLocaleDateString()}` };
      }

      // Mark as validated to track attempts (optional)
      await Voucher.markAsValidated(voucher.id);

      return { valid: true, voucher };
    } catch (error) {
      logger.error('Error validating voucher:', error);
      throw error;
    }
  },

  /**
   * Mark a voucher as used and associate with applicant
   * @param {string} voucherId 
   * @param {string} applicantId 
   */
  async useVoucher(voucherId, applicantId) {
    try {
      const result = await Voucher.markAsUsed(voucherId, applicantId);
      if (result) {
        logger.info(`Voucher ${voucherId} marked as used by applicant ${applicantId}`);
      }
      return result;
    } catch (error) {
      logger.error(`Failed to mark voucher ${voucherId} as used:`, error);
      throw error;
    }
  },

  /**
   * Bulk generate vouchers for admins
   * @param {string} adminId - Admin ID generating the vouchers
   * @param {number} count - Number of vouchers to create
   * @param {Date} expiresAt - Expiry date
   * @param {string} notes - Optional notes
   */
  async generateBatch(adminId, count, expiresAt, notes = null) {
    try {
      const vouchers = [];
      const defaultExpiry = new Date();
      defaultExpiry.setDate(defaultExpiry.getDate() + 31); // Default 31 days

      for (let i = 0; i < count; i++) {
        // Use centralized generators for consistent format across all voucher creation methods
        vouchers.push({
          code: generateVoucherCode(),
          serialNumber: generateSerialNumber(),
          pinCode: generatePinCode(),
          expiresAt: expiresAt || defaultExpiry,
          notes: notes || `Batch generated by admin ${adminId}`
        });
      }

      const results = await Voucher.createBatch(vouchers, adminId);
      logger.info(`Batch of ${count} vouchers generated by admin ${adminId}`);
      return results;
    } catch (error) {
      logger.error('Error generating voucher batch:', error);
      throw error;
    }
  }
};

module.exports = VoucherService;
